# -*- coding: utf-8 -*-
"""12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPvtZy0xK2nN5k3JntDX75vrdR9KQe62
"""

import matplotlib.pyplot as plt
categories = ['A', 'B', 'C', 'D', 'E']
values = [4, 7, 1, 8, 5]
plt.bar(categories, values)

plt.xlabel('Categories')
plt.ylabel('Values')
plt.title('Simple Bar Plot')
plt.show()