# -*- coding: utf-8 -*-
"""13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14QQmmcd-j2-ajUWCpbHx3VBSYeqmYV7C
"""

import matplotlib.pyplot as plt  # Fixed spacing and import alias
import numpy as np               # Fixed spacing

# Generate random data from a standard normal distribution
data = np.random.randn(1000)

# Plot the histogram
plt.hist(data, bins=30, color='blue', edgecolor='black')
plt.title('Histogram')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.show()