# -*- coding: utf-8 -*-
"""14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hm6KIYkDkyjlHIv0-Qid-5xOGeh5HqHX
"""

import matplotlib.pyplot as plt  # Fixed spacing: "asplt" → "as plt"

x = [5, 7, 8, 7, 2, 17, 2, 9, 4, 11, 12, 9, 6]
y = [99, 86, 87, 88, 100, 86, 103, 87, 94, 78, 77, 85, 86]

plt.scatter(x, y, color='red')
plt.title('Scatter Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.show()