# -*- coding: utf-8 -*-
"""16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dgp5nINpH9O4ICmW3ReNOirNKyQOe1VT
"""

import matplotlib.pyplot as plt
sizes = [15, 30, 45, 10]
labels = ['A', 'B', 'C', 'D']
colors = ['gold', 'yellowgreen', 'lightcoral', 'lightskyblue']
plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', shadow=True,
startangle=140)
plt.title('Pie Chart')
plt.axis('equal')
plt.show()