# -*- coding: utf-8 -*-
"""17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BGCEfb4uiocxXVnUvUEiCFtQQckjbO3W
"""

import matplotlib.pyplot as plt
import numpy as np

data = [np.random.normal(0, std, 100) for std in range(1, 4)]


plt.boxplot(data)

plt.xlabel('Data Sets')
plt.ylabel('Values')
plt.title('Simple Box Plot')

plt.show()