# -*- coding: utf-8 -*-
"""18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VS3lwO7_Lbjwu_L0XuWMOCti7v1FdSIv
"""

import matplotlib.pyplot as plt

x1 = [1, 2, 3, 4, 5]
y1 = [2, 3, 4, 5, 6]

x2 = [2, 3, 4, 5, 6]
y2 = [3, 4, 5, 6, 7]

x3 = [1, 3, 4, 7, 8]
y3 = [5, 3, 8, 3, 5]

plt.scatter(x1, y1, color='red', label='Dataset 1')
plt.scatter(x2, y2, color='blue', label='Dataset 2')
plt.scatter(x3, y3, color='green', label='Dataset 3')

plt.xlabel('X-axis label')
plt.ylabel('Y-axis label')
plt.title('Multiple Scatter Plots')
plt.legend()
plt.show()