# -*- coding: utf-8 -*-
"""7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eW5KAlXafzUrqW2jjt56y3Zv7Qp2hp2K
"""

import numpy as np
# Creating a 1D array
array = np.arange(12)
print("Original array:", array)
# Reshaping to 2D array (3x4)
reshaped_array = array.reshape((3, 4))
print("Reshaped to 3x4:\n", reshaped_array)
# Reshaping to 3D array (2x3x2)
reshaped_array_3d = array.reshape((2, 3, 2))
print("Reshaped to 2x3x2:\n", reshaped_array_3d)